### ISSUE TITLE
Implement rule: an instance of NonSortal must be specialized by an instance of Sortal or specialize an instance of NonSortal which is specialized by an instance of Sortal

### ISSUE THREAD

**Issue by lcbarcellos** [nemo-ufes/ufo-protege-plugin#9]
## Rule
An instance of [`gufo:NonSortal`](http://purl.org/nemo/gufo#NonSortal) must be specialized by an instance of [`gufo:Sortal`](http://purl.org/nemo/gufo#Sortal) or specialize an instance of [`gufo:NonSortal`](http://purl.org/nemo/gufo#NonSortal) which satisfies the first constraint (is specialized by an instance of [`gufo:Sortal`](http://purl.org/nemo/gufo#Sortal)).

## Source
Eighth rule from Table 1 of paper [Endurant Types in Ontology-Driven ConceptualModeling: Towards OntoUML 2.0](https://nemo.inf.ufes.br/wp-content/papercite-data/pdf/endurant_types_in_ontology_driven_conceptual_modeling__towards_ontouml_2_0_2018.pdf), presented on page 13 of document.

> From (t16), given a non-sortal N, there must be a sortal S that specializes N, or specializes a non-sortal supertype common to both N and S.

**Comment by jpalmeida** [comment]
I agree. Let's bear in  mind  that  this constraint  will often  be invalidated in more general ontologies (such as core ontologies). Further, because of how OWL works, it is possible for an object to be declared to instantiate a `gufo:NonSortal` and an unrelated `gufo:Sortal` (i.e., without a sortal specializing the non-sortal). Hence this rule should be at "info"  level, rather than "warning".
